var dataset = [
  {
    "publish_name": "tpch_partsupp",
    "incremental_load": false,
    "protocol": "file",
    "name": "tpch_partsupp",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "tpch_partsupp",
    "headers": [
      "partkey",
      "suppkey",
      "availqty",
      "suppycost",
      "comment"
    ],
    "endpoint": false,
    "separator": "|",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/tpch_partsupp",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "bl_top_movies",
    "incremental_load": false,
    "protocol": "file",
    "name": "bl_top_movies",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "bl_top_movies",
    "headers": [
      "ranking",
      "film",
      "casting",
      "verdict",
      "year",
      "net_gross",
      "lead_actor_one",
      "lead_actor_two"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/bl_top_movies",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "published_brands_data",
    "incremental_load": false,
    "protocol": "file",
    "name": "brand_basedata",
    "header": false,
    "deleted": false,
    "source_dashboard": "branderstanding_id",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "brand_basedata",
    "headers": [
      "ranks",
      "img_url",
      "brand(string)",
      "region",
      "country",
      "sector",
      "current_value(number)",
      "changed_value",
      "year"
    ],
    "endpoint": false,
    "separator": "|",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/branderstanding_id/data/brand_basedata",
    "remote": false,
    "type": "source",
    "overwrite": false
  },
  {
    "publish_name": "ib_yoe",
    "incremental_load": false,
    "protocol": "file",
    "name": "ib_yoe",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "ib_yoe",
    "headers": [
      "brand_name",
      "country",
      "sector",
      "yr_of_est"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/ib_yoe",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "bl_filmfare_nomin",
    "incremental_load": false,
    "protocol": "file",
    "name": "bl_filmfare_nomin",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "bl_filmfare_nomin",
    "headers": [
      "year",
      "movie"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/bl_filmfare_nomin",
    "remote": false,
    "overwrite": true
  },
  {
    "endpoint": true,
    "name": "WaitingTime",
    "source": "WaitingTime.csv",
    "headers": [
      "department_process",
      "patient_id",
      "mrn",
      "waiting_time_hrs",
      "department",
      "procedures"
    ],
    "separator": ",",
    "type": "source"
  },
  {
    "publish_name": "lang_greeting",
    "incremental_load": false,
    "protocol": "file",
    "name": "lang_greeting",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "lang_greeting",
    "headers": [
      "language(string)",
      "greeting(string)"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/lang_greeting",
    "remote": false,
    "overwrite": true
  },
  {
    "headers": [
      "Region",
      "Account_Segment",
      "Status",
      "ORG_PARTY_ID",
      "CONTACT_PARTY_ID",
      "NUM_LICENCES"
    ],
    "endpoint": true,
    "separator": ",",
    "name": "AllContactList",
    "source": "AllContactList.csv"
  },
  {
    "publish_name": "TpchPart",
    "incremental_load": false,
    "protocol": "file",
    "name": "TpchPart",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "TpchPart",
    "headers": [
      "part_key(number)",
      "name(string)",
      "mfgr(string)",
      "brand(string)",
      "type(string)",
      "size(number(10-5))",
      "container(string)",
      "retail_price(number(10-5))",
      "comment(text)"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/TpchPart",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "rem_personnel_facility",
    "incremental_load": false,
    "protocol": "file",
    "name": "rem_personnel_facility",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "rem_personnel_facility",
    "headers": [
      "location",
      "facility",
      "strength"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/rem_personnel_facility",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "country_flags",
    "incremental_load": false,
    "protocol": "file",
    "name": "country_flags",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "country_flags",
    "headers": [
      "country_code",
      "flag_image"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/country_flags",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "bl_yearofbirth_stars",
    "incremental_load": false,
    "protocol": "file",
    "name": "bl_yearofbirth_stars",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "bl_yearofbirth_stars",
    "headers": [
      "actor_actress",
      "year_of_birth",
      "gender"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/bl_yearofbirth_stars",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "TpchLineItem",
    "incremental_load": false,
    "protocol": "file",
    "name": "TpchLineItem",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "TpchLineItem",
    "headers": [
      "order_key(number)",
      "part_key(number)",
      "supp_key(number)",
      "line_number(number)",
      "quantity(number)",
      "extended_price(number(10-5))",
      "discount(number)",
      "tax(number)",
      "return_flag(string)",
      "line_status(string)",
      "ship_date(string)",
      "commit_date(number(15))",
      "receipt_date(string)",
      "ship_instruct(string)",
      "ship_mode(string)",
      "comment(text)"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/TpchLineItem",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "te_winners_info",
    "incremental_load": false,
    "protocol": "file",
    "name": "te_winners_info",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "te_winners_info",
    "headers": [
      "number",
      "player_name",
      "category",
      "dob",
      "country_code"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/te_winners_info",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "ib_list",
    "incremental_load": false,
    "protocol": "file",
    "name": "ib_list",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "ib_list",
    "headers": [
      "year",
      "ranking",
      "brand_name",
      "country",
      "sector",
      "brand_value",
      "bv_change"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/ib_list",
    "remote": false,
    "overwrite": true
  },
  {
    "headers": [
      "department",
      "admitting_physician_desc",
      "ward_facility",
      "bed_no",
      "patient_id",
      "mrn",
      "admission_date",
      "admission_time",
      "discharge_date",
      "discharge_time",
      "sex",
      "date_Of_birth",
      "age",
      "length_of_stay",
      "modeofpayment",
      "insurancescheme",
      "modes",
      "total_charges",
      "total_paid",
      "procedures",
      "ot_room",
      "ot_hrs",
      "occupacy",
      "admission_date_modified",
      "discharge_time_hrs"
    ],
    "endpoint": true,
    "name": "HealthcareRawData",
    "source": "HealthcareRawData.csv"
  },
  {
    "publish_name": "co_population",
    "incremental_load": false,
    "protocol": "file",
    "name": "co_population",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "co_population",
    "headers": [
      "country",
      "yr",
      "population"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/co_population",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "resultdata",
    "incremental_load": false,
    "protocol": "file",
    "name": "result",
    "header": false,
    "deleted": false,
    "source_dashboard": "featuredashboard",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "result",
    "headers": [
      "brand",
      "feature",
      "weight(number(10-2))"
    ],
    "endpoint": false,
    "separator": "\\t",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/featuredashboard/data/result",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "ol_gdp_percapita",
    "incremental_load": false,
    "protocol": "file",
    "name": "ol_gdp_percapita",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "ol_gdp_percapita",
    "headers": [
      "country",
      "year",
      "gdp"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/ol_gdp_percapita",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "co_capital_currency",
    "incremental_load": false,
    "protocol": "file",
    "name": "co_capital_currency",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "co_capital_currency",
    "headers": [
      "country",
      "capital",
      "currency",
      "language",
      "continent"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/co_capital_currency",
    "remote": false,
    "overwrite": true
  },
  {
    "headers": [
      "Business_Relation",
      "Lead_Response_Category",
      "Roles",
      "ORG_PARTY_ID",
      "CONTACT_PARTY_ID",
      "ContactStatus",
      "dummy"
    ],
    "endpoint": true,
    "separator": ",",
    "name": "AccountContact",
    "source": "AccountContact.csv"
  },
  {
    "publish_name": "tpch_lineitem",
    "incremental_load": false,
    "protocol": "file",
    "name": "tpch_lineitem",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "tpch_lineitem",
    "headers": [
      "orderkey",
      "partkey",
      "suppkey",
      "linenumber",
      "quantity",
      "extendedprice",
      "discount",
      "tax",
      "returnflag",
      "linestatus",
      "shipdate",
      "commitdate(number(15))",
      "receiptdate",
      "shipinstruct",
      "shipmode",
      "comment"
    ],
    "endpoint": false,
    "separator": "|",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/tpch_lineitem",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "ol_cntr_population",
    "incremental_load": false,
    "protocol": "file",
    "name": "ol_cntr_population",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "ol_cntr_population",
    "headers": [
      "country",
      "year",
      "population"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/ol_cntr_population",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "country_codes",
    "incremental_load": false,
    "protocol": "file",
    "name": "country_codes",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "country_codes",
    "headers": [
      "country_code",
      "country_name"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/country_codes",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "te_women_ranking",
    "incremental_load": false,
    "protocol": "file",
    "name": "te_women_ranking",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "te_women_ranking",
    "headers": [
      "ranking",
      "player",
      "first_name",
      "last_name",
      "country",
      "points",
      "ranking_date"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/te_women_ranking",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "te_men_ranking",
    "incremental_load": false,
    "protocol": "file",
    "name": "te_men_ranking",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "te_men_ranking",
    "headers": [
      "ranking",
      "player",
      "first_name",
      "last_name",
      "country",
      "points",
      "ranking_date",
      "week_change",
      "tournaments"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/te_men_ranking",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "resultdata_pig",
    "incremental_load": false,
    "protocol": "file",
    "name": "result",
    "header": false,
    "deleted": false,
    "source_dashboard": "featuredashboard_pig",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "result",
    "headers": [
      "brand",
      "feature",
      "weight(number(10-2))"
    ],
    "endpoint": false,
    "separator": "\\t",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/featuredashboard_pig/data/result",
    "remote": false,
    "overwrite": true
  },

  // ---------------------MYDATA------------------------------

  {
    "publish_name": "resultdata_pig",
    "incremental_load": false,
    "protocol": "file",
    "name": "result_seg_1",
    "header": false,
    "deleted": false,
    "source_dashboard": "segment_mktg1_dir1",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "result",
    "headers": [
      "brand",
      "feature",
      "weight(number(10-2))"
    ],
    "endpoint": false,
    "separator": "\\t",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/featuredashboard_pig/data/result",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "resultdata_pig",
    "incremental_load": false,
    "protocol": "file",
    "name": "result_seg_2",
    "header": false,
    "deleted": false,
    "source_dashboard": "segment_mktg1_dir1",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "result",
    "headers": [
      "brand",
      "feature",
      "weight(number(10-2))"
    ],
    "endpoint": false,
    "separator": "\\t",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/featuredashboard_pig/data/result",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "resultdata_pig",
    "incremental_load": false,
    "protocol": "file",
    "name": "result_seg_3",
    "header": false,
    "deleted": false,
    "source_dashboard": "segment_mktg1_dir1",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "result",
    "headers": [
      "brand",
      "feature",
      "weight(number(10-2))"
    ],
    "endpoint": false,
    "separator": "\\t",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/featuredashboard_pig/data/result",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "resultdata_pig",
    "incremental_load": false,
    "protocol": "file",
    "name": "result_seg_4",
    "header": false,
    "deleted": false,
    "source_dashboard": "segment_mktg1_dir2",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "result",
    "headers": [
      "brand",
      "feature",
      "weight(number(10-2))"
    ],
    "endpoint": false,
    "separator": "\\t",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/featuredashboard_pig/data/result",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "resultdata_pig",
    "incremental_load": false,
    "protocol": "file",
    "name": "result_seg_5",
    "header": false,
    "deleted": false,
    "source_dashboard": "segment_mktg1_dir2",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "result",
    "headers": [
      "brand",
      "feature",
      "weight(number(10-2))"
    ],
    "endpoint": false,
    "separator": "\\t",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/featuredashboard_pig/data/result",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "resultdata_pig",
    "incremental_load": false,
    "protocol": "file",
    "name": "result_seg_6",
    "header": false,
    "deleted": false,
    "source_dashboard": "segment_mktg2_dir1",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "result",
    "headers": [
      "brand",
      "feature",
      "weight(number(10-2))"
    ],
    "endpoint": false,
    "separator": "\\t",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/featuredashboard_pig/data/result",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "resultdata_pig",
    "incremental_load": false,
    "protocol": "file",
    "name": "result_seg_7",
    "header": false,
    "deleted": false,
    "source_dashboard": "segment_mktg2_dir1",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "result",
    "headers": [
      "brand",
      "feature",
      "weight(number(10-2))"
    ],
    "endpoint": false,
    "separator": "\\t",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/featuredashboard_pig/data/result",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "resultdata_pig",
    "incremental_load": false,
    "protocol": "file",
    "name": "result_seg_8",
    "header": false,
    "deleted": false,
    "source_dashboard": "segment_mktg2_dir2",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "result",
    "headers": [
      "brand",
      "feature",
      "weight(number(10-2))"
    ],
    "endpoint": false,
    "separator": "\\t",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/featuredashboard_pig/data/result",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "resultdata_pig",
    "incremental_load": false,
    "protocol": "file",
    "name": "result_seg_9",
    "header": false,
    "deleted": false,
    "source_dashboard": "segment_mktg2_dir2",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "result",
    "headers": [
      "brand",
      "feature",
      "weight(number(10-2))"
    ],
    "endpoint": false,
    "separator": "\\t",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/featuredashboard_pig/data/result",
    "remote": false,
    "overwrite": true
  },

  {
    "publish_name": "resultdata_pig",
    "incremental_load": false,
    "protocol": "file",
    "name": "result_seg_10",
    "header": false,
    "deleted": false,
    "source_dashboard": "segment_mktg2_dir2",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "result",
    "headers": [
      "brand",
      "feature",
      "weight(number(10-2))"
    ],
    "endpoint": false,
    "separator": "\\t",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/featuredashboard_pig/data/result",
    "remote": false,
    "overwrite": true
  },

  // ----------------------/MYDATA-----------------------------
  {
    "publish_name": "USCanadaBankData_1",
    "incremental_load": false,
    "protocol": "file",
    "name": "USCanadaBankSegment",
    "header": false,
    "deleted": false,
    "source_dashboard": "segment_mktg1",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "USCanadaBankSegment",
    "headers": [
      "ORG_PARTY_ID",
      "GU_PARTY_ID",
      "HQ_PARTY_ID",
      "PARENT_PARTY_ID",
      "LAST_TRANSACTION_DT",
      "LAST_SOURCE_SYSTEM",
      "PARTY_UPDATE_DATE",
      "PARTY_STATUS_CODE",
      "INTRODUCTION_SOURCE_SYSTEM",
      "INTRODUCTION_DATE",
      "ENCODING_CODE",
      "PRIMARY_NAME",
      "SECONDARY_NAME",
      "CISCO_COMPETITOR_ROLE",
      "PARTNER_SITE_ROLE",
      "UNREGISTERED_PARTY_FLAG",
      "LINE_1_ADDRESS",
      "LINE_2_ADDRESS",
      "LINE_3_ADDRESS",
      "LINE_4_ADDRESS",
      "CITY",
      "STATE_OR_PROVINCE_NAME",
      "COUNTY_NAME",
      "POSTAL_CODE",
      "ISO_COUNTRY_CODE",
      "ISO_COUNTRY_NAME",
      "POSTAL_THEATRE",
      "MKTG_REGION",
      "TELEPHONE_COUNTRY_CODE",
      "TELEPHONE_AREA_CODE",
      "TELEPHONE_NUMBER",
      "TELEPHONE_EXTENSION_NUMBER",
      "DUNS_NUMBER",
      "ACTIVITY_INDICATOR",
      "ANNUAL_SALES_INDICATOR",
      "ANNUAL_SALES_LOCAL",
      "ANNUAL_SALES_USD",
      "CURRENCY_CODE",
      "EMPLOYEES_COUNT",
      "EMPLOYEES_HERE_IND",
      "EMPLOYEES_TOTAL",
      "EMPLOYEES_TOTAL_IND",
      "HQ_BRANCH_CODE",
      "IMP_EXP_AGT_INDICATOR",
      "LEGAL_STATUS_CODE",
      "LINE_OF_BUSINESS",
      "GOVT_IDENTIFICATION_NUMBER",
      "GOVT_IDENTIFICATION_SYSTEM",
      "FAMILY_SITES_COUNT",
      "SIC_CODE",
      "SIC_CODE2",
      "SIC_CODE3",
      "SIC_CODE4",
      "SIC_CODE5",
      "SIC_CODE6",
      "SIC_CODE8",
      "SIC_CODE8_DESC",
      "SIC_DESC",
      "SIC_RANK",
      "SITE_CEO",
      "SITE_CEO_TITLE",
      "PARENT_SUBSIDIARY_CODE",
      "YEAR_ESTABLISHED_DATE",
      "PRINCIPLES_INDICATOR",
      "DNB_BUSINESS_NAME_KANJI",
      "DNB_BUSINESS_NAME_KANA",
      "OUT_OF_BUSINESS_FLAG",
      "REASON_CODE",
      "VERTICAL_MARKET_TOP",
      "VERTICAL_MARKET_SUB",
      "VERTICAL_MARKET_DETAIL",
      "VERTICAL_MARKET_SUB_DESC",
      "VERTICAL_MARKET_DETAIL_DESC",
      "VERTICAL_MARKET_TOP_DESC",
      "SALES_CHANNEL_CODE",
      "REP_ACCOUNT_TYPE",
      "REP_DUNS_NUMBER",
      "REP_DNB_LOB",
      "REP_SITE_TYPE",
      "REP_SITE_GROUP",
      "REP_SITE_REGION",
      "REP_NUM_SITES",
      "REP_NATIONAL_ID",
      "REP_SITE_IN_CHARGE_NAME",
      "REP_SITE_IN_CHARGE_TITLE",
      "REP_COMPANY_REVENUE",
      "REP_COMPANY_URL",
      "REP_SERVER_NUM",
      "REP_OWNER_LEVEL",
      "REP_PRIMARY_VERTICAL",
      "REP_SECONDARY_VERTICAL",
      "REP_TERTIARY_VERTICAL",
      "REP_FOURTH_VERTICAL",
      "REP_PRI_BIZ_1",
      "REP_PRI_BIZ_2",
      "REP_PRI_BIZ_3",
      "REP_TELEPHONE_NUMBER",
      "REP_NUM_TELEPHONE_EXT",
      "REP_NUM_EMPLOYEES",
      "REP_NUM_PC",
      "UPDATE_DATE",
      "REGIONAL_MKTG_BUSINESS_SEGMENT",
      "SFDC_ACCOUNT_ID",
      "NAMED_ACCOUNT_FLAG",
      "CUSTOMER_MARKET_SEGMENT",
      "BDO_UPDATE_DATE",
      "SALES_ACCOUNT_ID",
      "STATUS",
      "ACCOUNT_TYPE",
      "ACCOUNT_SUB_TYPE",
      "ACCOUNT_NAME",
      "ACCOUNT_VERTICAL_TOP_DESC",
      "ACCOUNT_VERTICAL_SUB_DESC",
      "ACCOUNT_SEGMENT",
      "ACCOUNT_SUB_SEGMENT",
      "SHARE_NODE_ID",
      "SHARE_NODE_NAME",
      "SHARE_NODE_NAME_LEVEL_1",
      "SHARE_NODE_NAME_LEVEL_2",
      "SHARE_NODE_NAME_LEVEL_3",
      "SHARE_NODE_NAME_LEVEL_4",
      "SHARE_NODE_NAME_LEVEL_5",
      "SHARE_NODE_NAME_LEVEL_6",
      "SHARE_NODE_NAME_LEVEL_7",
      "SHARE_NODE_SALES_COVERAGE",
      "SHARE_NODE_SUB_SALES_COVERAGE"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/segment_mktg1/data/USCanadaBankSegment",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "ol_game_categories",
    "incremental_load": false,
    "protocol": "file",
    "name": "ol_game_categories",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "ol_game_categories",
    "headers": [
      "event",
      "category",
      "type",
      "year_a",
      "year_b",
      "year_c",
      "year_d",
      "year_e",
      "event_type"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/ol_game_categories",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "advisor_details",
    "incremental_load": false,
    "protocol": "file",
    "name": "advisor_details",
    "header": false,
    "deleted": false,
    "source_dashboard": "Social_Influence",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "advisor_details",
    "headers": [
      "FirmName",
      "Advisor",
      "status",
      "Fund",
      "count(number(10))",
      "Gross_Amount_sum(number(10-2))"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/Social_Influence/data/advisor_details",
    "remote": false,
    "overwrite": true
  },
  {
    "headers": [
      "InstallBase",
      "Acc_Vertical",
      "Num_Licences_Range",
      "ORG_PARTY_ID",
      "CONTACT_PARTY_ID",
      "NUM_LICENCES"
    ],
    "endpoint": true,
    "separator": ",",
    "name": "AccountSales",
    "source": "AccountSales.csv"
  },
  {
    "publish_name": "rem_remedy_data",
    "incremental_load": false,
    "protocol": "file",
    "name": "rem_remedy_data",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "rem_remedy_data",
    "headers": [
      "status",
      "status_reason",
      "slm_status",
      "priority",
      "summary",
      "assigned_grp",
      "organization",
      "department",
      "location",
      "facility",
      "requestor_id",
      "escalated",
      "impact",
      "incident_type",
      "optier_one",
      "optier_two",
      "optier_three",
      "owner_support_organization",
      "pending_flag",
      "submit_date",
      "last_resol",
      "resolution",
      "total_transfers",
      "transfers_between_groups",
      "transfers_between_individuals",
      "urgency"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/rem_remedy_data",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "lang_family",
    "incremental_load": false,
    "protocol": "file",
    "name": "lang_family",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "lang_family",
    "headers": [
      "language(string)",
      "origin(string)"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/lang_family",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "ib_brand_info",
    "incremental_load": false,
    "protocol": "file",
    "name": "ib_brand_info",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "ib_brand_info",
    "headers": [
      "number",
      "brand",
      "logo_location",
      "company"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/ib_brand_info",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "mm_pivoted_dataa",
    "incremental_load": false,
    "protocol": "file",
    "name": "MarketMetricsPivoted",
    "header": false,
    "deleted": false,
    "source_dashboard": "market_metrics_datatask",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "MarketMetricsPivoted",
    "headers": [
      "AccountOwner",
      "broker_dealer",
      "street_address",
      "zip_code",
      "City",
      "Metro_area",
      "State",
      "Territory",
      "Category",
      "Category_value",
      "Company_Category(string(2000))",
      "Company_Category_value",
      "Company_Total_Opportunity",
      "Company_Total_Value"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/market_metrics_datatask/data/MarketMetricsPivoted",
    "remote": false,
    "type": "source",
    "overwrite": true
  },
  {
    "publish_name": "source_FS",
    "incremental_load": false,
    "protocol": "file",
    "name": "source_FS_published",
    "header": false,
    "deleted": false,
    "source_dashboard": "storagesink",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "source_FS_published",
    "headers": [
      "id",
      "name",
      "marks"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/storagesink/data/source_FS_published",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "tpch_region",
    "incremental_load": false,
    "protocol": "file",
    "name": "tpch_region",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "tpch_region",
    "headers": [
      "regionkey",
      "name",
      "comment"
    ],
    "endpoint": false,
    "separator": "|",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/tpch_region",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "co_percapita_gdp",
    "incremental_load": false,
    "protocol": "file",
    "name": "co_percapita_gdp",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "co_percapita_gdp",
    "headers": [
      "country",
      "yr",
      "gdp"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/co_percapita_gdp",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "TpchPartsUpp",
    "incremental_load": false,
    "protocol": "file",
    "name": "TpchPartsUpp",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "TpchPartsUpp",
    "headers": [
      "part_key(number)",
      "supp_key(number)",
      "avail_qty(number)",
      "supply_cost(number(10-5))",
      "comment(text)"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/TpchPartsUpp",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "tpch_supplier",
    "incremental_load": false,
    "protocol": "file",
    "name": "tpch_supplier",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "tpch_supplier",
    "headers": [
      "suppkey",
      "name",
      "address",
      "nationkey",
      "phone",
      "acctbal",
      "comment"
    ],
    "endpoint": false,
    "separator": "|",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/tpch_supplier",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "tpch_part",
    "incremental_load": false,
    "protocol": "file",
    "name": "tpch_part",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "tpch_part",
    "headers": [
      "partkey",
      "name",
      "mfgr",
      "brand",
      "type",
      "size",
      "container",
      "retailprice",
      "comment"
    ],
    "endpoint": false,
    "separator": "|",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/tpch_part",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "tpch_orders",
    "incremental_load": false,
    "protocol": "file",
    "name": "tpch_orders",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "tpch_orders",
    "headers": [
      "orderkey",
      "custkey",
      "orderstatus",
      "totalprice",
      "orderdate",
      "orderpriority",
      "clerk",
      "shippriority",
      "comment"
    ],
    "endpoint": false,
    "separator": "|",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/tpch_orders",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "te_player_style",
    "incremental_load": false,
    "protocol": "file",
    "name": "te_player_style",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "te_player_style",
    "headers": [
      "player_name",
      "style"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/te_player_style",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "tc_continentalUSA",
    "incremental_load": false,
    "protocol": "file",
    "name": "tc_continentalUSA",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "tc_continentalUSA",
    "headers": [
      "permalink",
      "company",
      "num_emps",
      "category",
      "city",
      "state",
      "funded_date",
      "raised_amt",
      "raised_currency",
      "round"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/tc_continentalUSA",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "TpchNation",
    "incremental_load": false,
    "protocol": "file",
    "name": "TpchNation",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "TpchNation",
    "headers": [
      "nation_key(number)",
      "name(string)",
      "region_key(number)",
      "comment(text)"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/TpchNation",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "TpchCustomer",
    "incremental_load": false,
    "protocol": "file",
    "name": "TpchCustomer",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "TpchCustomer",
    "headers": [
      "customer_key(number)",
      "name(string)",
      "address(string)",
      "nation_key(number)",
      "phone(string)",
      "acct_bal(number(10-5))",
      "makt_segment(string)",
      "comment(text)"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/TpchCustomer",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "tc_IPO",
    "incremental_load": false,
    "protocol": "file",
    "name": "tc_IPO",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "tc_IPO",
    "headers": [
      "serial_number",
      "company_name",
      "ipo",
      "ipo_date",
      "current_stock_price",
      "market_cap"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/tc_IPO",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "TpchRegion",
    "incremental_load": false,
    "protocol": "file",
    "name": "TpchRegion",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "TpchRegion",
    "headers": [
      "region_key(number)",
      "name(string)",
      "comment(text)"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/TpchRegion",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "co_exchange",
    "incremental_load": false,
    "protocol": "file",
    "name": "co_exchange",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "co_exchange",
    "headers": [
      "country",
      "yr",
      "exchange_"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/co_exchange",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "ol_all_medalists",
    "incremental_load": false,
    "protocol": "file",
    "name": "ol_all_medalists",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "ol_all_medalists",
    "headers": [
      "city",
      "edition",
      "sport",
      "discipline",
      "athlete",
      "noc",
      "gender",
      "event",
      "event_gender",
      "medal"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/ol_all_medalists",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "te_grandslam_winners",
    "incremental_load": false,
    "protocol": "file",
    "name": "te_grandslam_winners",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "te_grandslam_winners",
    "headers": [
      "year",
      "grand_slam",
      "winner",
      "category"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/te_grandslam_winners",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "resultdata_spark",
    "incremental_load": false,
    "protocol": "file",
    "name": "result",
    "header": false,
    "deleted": false,
    "source_dashboard": "featuredashboard_spark",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "result",
    "headers": [
      "brand",
      "feature",
      "weight(number(10-2))"
    ],
    "endpoint": false,
    "separator": "\\t",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/featuredashboard_spark/data/result",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "TpchOrderStatus",
    "incremental_load": false,
    "protocol": "file",
    "name": "TpchOrderStatus",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "TpchOrderStatus",
    "headers": [
      "order_key(number)",
      "customer_key(number)",
      "order_status(string)",
      "total_price(number(10-5))",
      "order_date(string)",
      "order_priority(string)",
      "clerk(string)",
      "ship_priority(number)",
      "comment(text)"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/TpchOrderStatus",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "TpchSupplier",
    "incremental_load": false,
    "protocol": "file",
    "name": "TpchSupplier",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "TpchSupplier",
    "headers": [
      "supp_key(number)",
      "name(string)",
      "address(string)",
      "nation_key(number)",
      "phone(string)",
      "acc_bal(string)",
      "comment(text)"
    ],
    "endpoint": false,
    "separator": "\\t",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/TpchSupplier",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "tpch_customer",
    "incremental_load": false,
    "protocol": "file",
    "name": "tpch_customer",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "tpch_customer",
    "headers": [
      "custkey",
      "name",
      "address",
      "nationkey",
      "phone",
      "acctbal",
      "mktsegment",
      "comment"
    ],
    "endpoint": false,
    "separator": "|",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/tpch_customer",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "geetmala_data_in_db",
    "incremental_load": false,
    "protocol": "file",
    "name": "geetmala_hdfs_endpoint_true_publish",
    "header": false,
    "deleted": false,
    "source_dashboard": "missing_features",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "geetmala_hdfs_endpoint_true_publish",
    "headers": [
      "year",
      "prank",
      "song",
      "singers",
      "musician",
      "lyricist",
      "movie",
      "actors"
    ],
    "endpoint": false,
    "separator": "\\t",
    "source": "/upload/missing_features/Geetmala.txt",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "derived_FS",
    "incremental_load": false,
    "protocol": "file",
    "name": "res_FS_published",
    "header": false,
    "deleted": false,
    "source_dashboard": "storagesink",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "res_FS_published",
    "headers": [
      "name",
      "marks"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/storagesink/data/res_FS_published",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "mm_pivoted_data",
    "incremental_load": false,
    "protocol": "file",
    "name": "MarketMetricsPivoted",
    "header": false,
    "deleted": false,
    "source_dashboard": "market_metrics",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "MarketMetricsPivoted",
    "headers": [
      "AccountOwner",
      "broker_dealer",
      "street_address",
      "zip_code",
      "City",
      "Metro_area",
      "State",
      "Territory",
      "Category",
      "Category_value",
      "Company_Category(string(2000))",
      "Company_Category_value",
      "Company_Total_Opportunity",
      "Company_Total_Value"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/market_metrics/data/MarketMetricsPivoted",
    "remote": false,
    "type": "source",
    "overwrite": true
  },
  {
    "publish_name": "derived_DB",
    "incremental_load": false,
    "protocol": "file",
    "name": "res_DB_published",
    "header": false,
    "deleted": false,
    "source_dashboard": "storagesink",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "res_DB_published",
    "headers": [
      "name",
      "marks"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/storagesink/data/res_DB_published",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "rem_emplist",
    "incremental_load": false,
    "protocol": "file",
    "name": "rem_emplist",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "rem_emplist",
    "headers": [
      "eid",
      "grade",
      "city",
      "bu",
      "location",
      "gender"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/rem_emplist",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "source_DB",
    "incremental_load": false,
    "protocol": "file",
    "name": "source_DB_published",
    "header": false,
    "deleted": false,
    "source_dashboard": "storagesink",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "source_DB_published",
    "headers": [
      "id",
      "name",
      "marks"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/storagesink/data/source_DB_published",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "ib_forbes",
    "incremental_load": false,
    "protocol": "file",
    "name": "ib_forbes",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "ib_forbes",
    "headers": [
      "year",
      "ranking",
      "company",
      "country",
      "sales",
      "profits",
      "assets",
      "market_value",
      "industry"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/ib_forbes",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "tc_state_population",
    "incremental_load": false,
    "protocol": "file",
    "name": "tc_state_population",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "tc_state_population",
    "headers": [
      "state",
      "year",
      "population"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/tc_state_population",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "tpch_nation",
    "incremental_load": false,
    "protocol": "file",
    "name": "tpch_nation",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "tpch_nation",
    "headers": [
      "nationkey",
      "name",
      "regionkey",
      "comment"
    ],
    "endpoint": false,
    "separator": "|",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/tpch_nation",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "bl_all_movies",
    "incremental_load": false,
    "protocol": "file",
    "name": "bl_all_movies",
    "header": false,
    "deleted": false,
    "source_dashboard": "common_datasets",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "bl_all_movies",
    "headers": [
      "year",
      "title",
      "director",
      "lead_actor_one",
      "lead_actor_two",
      "casting",
      "genre"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/common_datasets/data/bl_all_movies",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "mm_pivoted_dataa_spark",
    "incremental_load": false,
    "protocol": "file",
    "name": "MarketMetricsPivoted",
    "header": false,
    "deleted": false,
    "source_dashboard": "market_metrics_spark",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "MarketMetricsPivoted",
    "headers": [
      "AccountOwner",
      "broker_dealer",
      "street_address",
      "zip_code",
      "City",
      "Metro_area",
      "State",
      "Territory",
      "Category",
      "Category_value",
      "Company_Category(string(2000))",
      "Company_Category_value",
      "Company_Total_Opportunity",
      "Company_Total_Value"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/market_metrics_spark/data/MarketMetricsPivoted",
    "remote": false,
    "type": "source",
    "overwrite": true
  },
  {
    "publish_name": "geetmala_data_hdfs",
    "incremental_load": false,
    "protocol": "file",
    "name": "geetmala_hdfs_endpoint_false_publish",
    "header": false,
    "deleted": false,
    "source_dashboard": "missing_features",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "geetmala_hdfs_endpoint_false_publish",
    "headers": [
      "year",
      "prank",
      "song",
      "singers",
      "musician",
      "lyricist",
      "movie",
      "actors"
    ],
    "endpoint": false,
    "separator": "\\t",
    "source": "/upload/missing_features/Geetmala.txt",
    "remote": false,
    "overwrite": true
  },
  {
    "publish_name": "FirmWeightInFunds",
    "incremental_load": false,
    "protocol": "file",
    "name": "FirmWeightInFunds",
    "header": false,
    "deleted": false,
    "source_dashboard": "Social_Influence",
    "storage": "FS",
    "fs": "hdfs",
    "source_ds": "FirmWeightInFunds",
    "headers": [
      "firm",
      "Fund",
      "FirmName",
      "weight",
      "count(number(10))"
    ],
    "endpoint": false,
    "separator": ",",
    "source": "hdfs://selfserviceapp.shareinsights.com:8020/user/shareinsights/live/dashboards/Social_Influence/data/FirmWeightInFunds",
    "remote": false,
    "overwrite": true
  },
  {
    "endpoint": true,
    "protocol": "Interbranddata",
    "name": "BrandBaseData",
    "source": "http://interbrand.com/best-brands/best-global-brands/year/ranking/#?listFormat=ls",
    "file_format": "csv",
    "headers": [
      "ranks",
      "img_url",
      "brand(string)",
      "region",
      "country",
      "sector",
      "current_value(number)",
      "changed_value",
      "year"
    ],
    "separator": "|",
    "type": "source",
    "overwrite": false
  }
]
